name: app_fleet_webpage
description: A brilliant workspace manager & quick launcher for the Linux Desktops.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vector_graphics_compiler: ^1.1.7
  lottie: ^2.6.0
  vector_graphics: ^1.1.7
  flutter_svg: ^2.0.7
  flutter_animate: ^4.2.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/backgrounds/
    - assets/animations/
    - assets/images/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen/Sen-Medium.ttf
          weight: 500
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
        - asset: fonts/Sen/Sen-ExtraBold.ttf
          weight: 900